### ISSUE TITLE
Computer Architecture -> 计算机系统结构

### ISSUE THREAD

**Issue by enochii** [keithnull/TeachYourselfCS-CN#14]
感谢译者。[这里](https://github.com/keithnull/TeachYourselfCS-CN/blob/master/TeachYourselfCS-CN.md#%E8%AE%A1%E7%AE%97%E6%9C%BA%E6%9E%B6%E6%9E%84) 把 Computer Architecture 翻译为 “计算机架构”，国内翻译更偏向 “计算机系统结构”，如果有需要我可以帮忙修改。

**Comment by keithnull** [comment]
是的，国内的课程和教材确实是「计算机系统结构」的用法比较多，「计算机架构」有一点别扭。

感谢提出，以及欢迎帮忙修改~
