### ISSUE TITLE
《计算机程序的构造和解释》国内替换源

### ISSUE THREAD

**Issue by sandhiker** [keithnull/TeachYourselfCS-CN#3]
主要是伯克利的课程我这打不开（不翻的话），我搜了一下相关视频，有点多，直接 PR 不知道如何考量应该怎样替换，所以就提个 issue。

- MIT 经典公开课（中英字幕）：https://www.bilibili.com/video/av8515129/

- 应该是伯克利 Scheme 版本最后一次公开课（英文字幕）：https://www.bilibili.com/video/av40460492/

- 伯克利 2018 年春课程（英文字幕，有部分字幕缺失）：https://www.bilibili.com/video/av20538548

- 伯克利 2019 年夏课程（中英字幕，中文机翻）：https://www.bilibili.com/video/av82503560

**Comment by sandhiker** [comment]
其它建议：学习这门课如果采用 scheme 还可以把这个 Github 关联上
https://github.com/DeathKing/Learning-SICP
我之前学 MIT 课程的时候就有些不知所措，这个项目提供了 Scheme 入门，环境配置，习题解答，课程作业等一系列相关资源，作为国内自学 Scheme 是一个很好的入口。

**Comment by keithnull** [comment]
很不错的建议，要不你开个PR吧～如果觉得内容不便直接添加到文档，可以考虑在文档中链接到此Issue？
