### ISSUE TITLE
原文有更新

### ISSUE THREAD

**Issue by thinker1990** [keithnull/TeachYourselfCS-CN#7]
1. Computer Architecture  推荐阅读改为： Computer Systems: A Programmer's Perspective.
2. Languages and Compilers 推荐阅读改为： Crafting Interpreters.
3. Distributed Systems 推荐阅读改为： Designing Data-Intensive Applications.

**Comment by keithnull** [comment]
Thanks for this information. Would you please make a pull request? I'll merge it.

**Comment by thinker1990** [comment]
Sure, I will try to translate the update this weekend.
