### ISSUE TITLE
我就提个issue 

### ISSUE THREAD

**Issue by Deniffer** [keithnull/TeachYourselfCS-CN#9]
没有捐献渠道吗？ 我感觉写得太棒了！

**Comment by keithnull** [comment]
Thanks very much for your support~

However, as a community, we made this translation just out of interest and for sharing spirits. So no donation is needed.

Please feel free to learn and explore with this material~ : )

---

十分感谢你的支持~

不过，作为一个社区（不只是我一个人），我们完全是出于兴趣和共享精神来翻译了这份文档。所以我们不需要捐献。

自由地用这份文档来学习和探索广阔的计算机科学世界吧！
